### PR TITLE
Remove parsing of error key's condition field

### LINKED ISSUE #255: Stop parsing condition field

### PR DESCRIPTION
**Pull request by epapbak**
# Description

Condition field has been deprecated from the provided rules. This commit removes the related code in this service.

Fixes #255

## Type of change

- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Documentation update

## Testing steps

Running UTs + testing the service manually

## Checklist
* [x] `make before_commit` passes
* [x] updated documentation wherever necessary
* [x] added or modified tests if necessary
* [x] updated schemas and validators in [insights-data-schemas](https://github.com/RedHatInsights/insights-data-schemas) in case of input/output change

### CODE REVIEW

**Review by tisnik — COMMENTED** [review]
Is not docs generated automatically on CI?

**Comment by epapbak** [comment]
> Is not docs generated automatically on CI?

It is, it is =)

**Review by tisnik — APPROVED** [review]
LGTM

**Review by Bee-lee — APPROVED** [review]
LGTM, thanks

**Pull request merged**
