### PR TITLE
fix-143

### LINKED ISSUE #143: Not serving appropriate rule content when an error happens while parsing
When the service tries to parse the rules content at start up, if it fails to parse some rule, the service continue working but any of the valid rules is properly served.

Proposed solutions:

1. Quick & dirty: when it fails to parse something, just end the program, so it is easily visible that something went wrong
2. Recover from the problem and serve the rest of well-defined rules

### PR DESCRIPTION
**Pull request by Sergey1011010**
# Description

Fixes #143

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Testing steps

`make before_commit`

### CODE REVIEW

**Review by tisnik — APPROVED** [review]
LGTM!
(probably the first use of `continue` in our code? :)

**Comment by Sergey1011010** [comment]
@tisnik not really :) 
```
> ./grep --include="*.go" -ir 'continue'
insights-content-service/content/content.go:                                    continue
insights-results-aggregator/consumer/benchmark_test.go:                                 continue
insights-results-aggregator/consumer/benchmark_test.go:                                 continue
insights-results-aggregator/conf/configuration.go:                      continue // skip header
insights-results-smart-proxy/server/handlers.go:                        continue
insights-results-smart-proxy/server/handlers.go:                        continue
insights-results-smart-proxy/conf/configuration.go:                     continue // skip header
insights-results-smart-proxy/content/parsing.go:                                continue
```

**Comment by joselsegura** [comment]
`./grep`: don't you have it installed properly? :-D

About the commit, LGTM

> @tisnik not really :)
> 
> ```
> > ./grep --include="*.go" -ir 'continue'
> insights-content-service/content/content.go:                                    continue
> insights-results-aggregator/consumer/benchmark_test.go:                                 continue
> insights-results-aggregator/consumer/benchmark_test.go:                                 continue
> insights-results-aggregator/conf/configuration.go:                      continue // skip header
> insights-results-smart-proxy/server/handlers.go:                        continue
> insights-results-smart-proxy/server/handlers.go:                        continue
> insights-results-smart-proxy/conf/configuration.go:                     continue // skip header
> insights-results-smart-proxy/content/parsing.go:                                continue
> ```

**Review by joselsegura — APPROVED** [review]

**Comment by tisnik** [comment]
> `./grep`: don't you have it installed properly? :-D
> 
> About the commit, LGTM
> 
> > @tisnik not really :)
> > ```
> > > ./grep --include="*.go" -ir 'continue'
> > insights-content-service/content/content.go:                                    continue
> > insights-results-aggregator/consumer/benchmark_test.go:                                 continue
> > insights-results-aggregator/consumer/benchmark_test.go:                                 continue
> > insights-results-aggregator/conf/configuration.go:                      continue // skip header
> > insights-results-smart-proxy/server/handlers.go:                        continue
> > insights-results-smart-proxy/server/handlers.go:                        continue
> > insights-results-smart-proxy/conf/configuration.go:                     continue // skip header
> > insights-results-smart-proxy/content/parsing.go:                                continue
> > ```

Ah, at least we have just few `fallthrough`s (all written by me, oh :-o )

**Comment by Sergey1011010** [comment]
@joselsegura, I do ;)

```
> cat grep
#!/usr/bin/env bash

# TODO: fix colors issue(there's no colors in the output)

grep --exclude-dir="docs/" "$@"
```

**Review by quarckster — APPROVED** [review]

**Pull request merged**
